server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: shermatov
    password: superSecret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet